name: Create File in EC2 Instance

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Execute commands on EC2 instance
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        PASSWORD: ${{ secrets.EC2_PASSWORD }}
      shell: pwsh
      run: |
        echo "$env:PRIVATE_KEY" > private_key.pem
        # Setting permissions in PowerShell
        Invoke-Expression "icacls .\private_key.pem /inheritance:r"
        Invoke-Expression "icacls .\private_key.pem /grant:r `$env:USERNAME`:`(R`)"
        
        # Debugging: Ensure that environment variables are set correctly
        Write-Output "HOST: $env:HOST"
        Write-Output "USERNAME: $env:USERNAME"
        
        # Running SSH command
        echo "Creating file on EC2 instance..."
        chmod +x private_key.pem
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem "$env:USERNAME@$env:HOST" "echo 'Username: $env:USERNAME\nPassword: $env:PASSWORD' > D:\myfile.txt"
        
        echo "File created."
