name: Create File in EC2 Instance

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Execute commands on EC2 instance
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        PASSWORD: ${{ secrets.EC2_PASSWORD }}
      shell: pwsh
      run: |
        # Output environment variable values for debugging (avoid outputting sensitive information)
        Write-Output "HOST: $env:HOST"
        Write-Output "USERNAME: $env:USERNAME"
        
        # Write the private key to a file and set permissions
        echo "$env:PRIVATE_KEY" > private_key.pem
        Invoke-Expression "icacls .\private_key.pem /inheritance:r"
        Invoke-Expression "icacls .\private_key.pem /grant:r `$env:USERNAME`:`(R`)"
        
        # Running SSH command and checking the return value
        echo "Creating file on EC2 instance..."
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem "$env:USERNAME@$env:HOST" "echo 'Username: $env:USERNAME\nPassword: $env:PASSWORD' > D:\myfile.txt" 2>&1 | Write-Output
        if ($LASTEXITCODE -ne 0) {
          Write-Error "SSH command failed with exit code $LASTEXITCODE"
          exit 1
        }

        echo "File created."
